version: "3.3"

services:
  erp:
    image: erpserver
    ports:
      - 8069:8069
      - 8068:8068   

  postgres:
    image: postgres:developer
    ports:
      - 5432:5432

  mongo:
    image: mongo:3.0
    ports: 
      - 27017:27017

  redis:
    image: redis:5.0
    ports:
      - 6379:6379

